"use client";

import { Section } from "@/components/ui/section";
import { motion } from "framer-motion";
import { Aperture, Star } from "lucide-react";

export function RealisticGenSection({ theme }: { theme?: "dark" | "light" }) {
    return (
        <Section id="realistic-gen" className="bg-transparent" theme={theme}>
            <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center gap-16">
                <div className="flex-1 space-y-6">
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-rose-500/20 bg-rose-500/5">
                        <Aperture size={16} className="text-rose-500" />
                        <span className="text-sm text-rose-500 font-medium">Hyper-Realistic AI</span>
                    </div>
                    <h2 className="font-display font-bold text-4xl md:text-5xl lg:text-6xl">
                        Blur the line between <br />
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-rose-500 to-red-400">
                            Real & AI
                        </span>
                    </h2>
                    <p className="text-lg opacity-60 leading-relaxed max-w-lg">
                        Generate photorealistic images that are indistinguishable from real photography. Perfect for stock photos, portraits, and detailed environments.
                    </p>

                    <div className="flex items-center gap-4 pt-4">
                        <div className="glass px-4 py-3 rounded-xl flex items-center gap-3">
                            <span className="font-bold text-2xl">8K</span>
                            <span className="text-xs opacity-60 uppercase tracking-wider">Resolution <br /> Support</span>
                        </div>
                        <div className="glass px-4 py-3 rounded-xl flex items-center gap-3">
                            <span className="font-bold text-2xl">V6</span>
                            <span className="text-xs opacity-60 uppercase tracking-wider">Latest <br /> Model</span>
                        </div>
                    </div>
                </div>

                <div className="flex-1 w-full">
                    <div className="grid grid-cols-1 gap-6">
                        <motion.div
                            initial={{ scale: 0.95, opacity: 0 }}
                            whileInView={{ scale: 1, opacity: 1 }}
                            transition={{ duration: 0.7 }}
                            className="aspect-[16/10] rounded-3xl overflow-hidden relative shadow-2xl group w-full"
                        >
                            {/* Main Realistic Image */}
                            <div className="w-full h-full bg-cover bg-center transition-transform duration-700 group-hover:scale-110" style={{ backgroundImage: 'url(https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1976&auto=format&fit=crop)' }}></div>

                            {/* Overlay Information */}
                            <div className="absolute inset-x-0 bottom-0 p-6 bg-gradient-to-t from-black/80 to-transparent">
                                <div className="flex items-center justify-between">
                                    <div>
                                        <p className="text-white text-sm font-medium">Portrait Mode</p>
                                        <div className="flex gap-1 text-yellow-400 mt-1">
                                            {[1, 2, 3, 4, 5].map(i => <Star key={i} size={12} fill="currentColor" />)}
                                        </div>
                                    </div>
                                    <span className="px-3 py-1 bg-white/20 backdrop-blur-md rounded-full text-xs text-white border border-white/10">
                                        Generated by AI
                                    </span>
                                </div>
                            </div>
                        </motion.div>
                    </div>
                </div>
            </div>
        </Section>
    );
}
